name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Summary-Care-Record-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml

# This pipeline gets executed when we merge to master.
# So, it's presumed that internal-dev has already passed because otherwise you couldn't
# have merged in. This file requires manual approval deploy to production. So only approve
# (by clicking review/approve in Azure DevOps UI) if that's what you want to do.
# The azure-release-pipeline.yml contains the regular internal-dev deployment pipeline. 
# That is where your pr branches will live.
extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    prod_producer_approval: true
    enable_monitoring: true
    enable_status_monitoring: true
    jinja_templates:
      REQUIRE_ASID: true
    apigee_deployments:
      - environment: int
        jinja_templates:
          REQUIRE_ASID: false
        post_deploy:
          - template: ./templates/run-tests-int.yml
            parameters:
              smoke_tests: true
      - environment: prod
        depends_on:
          - int
        jinja_templates:
          REQUIRE_ASID: false
        post_deploy:
          - template: ./templates/run-tests-prod.yml
