name: "$(SourceBranchName)+$(BuildID)"

trigger: none
pr: none

resources:
  repositories:
    - repository: common
      type: github
      name: NHSDigital/api-management-utils
      ref: refs/heads/edge
      endpoint: NHSDigital
  pipelines:
  - pipeline: build_pipeline
    source: "Summary-Care-Record-Build"
    trigger:
      branches:
        include:
          - refs/tags/v*

pool:
  name: 'AWS-ECS'

variables:
  - template: project.yml


# This pipeline gets executed when we commit a new feature branch (to internal-dev).
# It will execute more advanced smoketests than int or prod.
# This deploy does not include the prod environment as that can only occur once you merge 
# into master, which will execue the azure-release-pipeline-master.yml file.
extends:
  template: azure/common/apigee-deployment.yml@common
  parameters:
    service_name: ${{ variables.service_name }}
    short_service_name: ${{ variables.short_service_name }}
    service_base_path: ${{ variables.service_base_path }}
    prod_producer_approval: true
    enable_monitoring: true
    enable_status_monitoring: true
    jinja_templates:
      REQUIRE_ASID: true
    apigee_deployments:
      - environment: internal-dev
        post_deploy:
          - template: ./templates/run-tests.yml
            parameters:
              smoke_tests: true
      - environment: int
        depends_on:
          - internal_dev
        jinja_templates:
          REQUIRE_ASID: false
        post_deploy:
          - template: ./templates/run-tests-int.yml
            parameters:
              smoke_tests: true
